"""Pytest plugin for automatic call graph tracing during test execution.

This module provides two integration modes:

1. **conftest.py generation**: Generate a conftest.py that auto-activates
   the tracer when pytest starts, and exports the call graph when done.

2. **Pytest plugin class**: Can be registered programmatically via
   pytest's plugin system for finer control.

Usage in CI:
    # Generate conftest.py in project root
    python -m cintent_v3 generate-conftest /path/to/project

    # Run tests normally — tracing happens automatically
    cd /path/to/project && pytest

    # The call graph JSON is written to cintent_v3_callgraph.json
"""

from __future__ import annotations

import json
import os
import sys
from typing import Any

from cintent_v3.callgraph import export_call_graph
from cintent_v3.tracer import CallGraphTracer


CONFTEST_TEMPLATE = '''"""Auto-generated by cintent_v3 for call graph tracing.

This conftest.py installs a deterministic call graph tracer that captures
every function call during pytest execution. The call graph is exported
to JSON when the test session finishes.

CI Integration:
    Set CINTENT_V3_ENABLED=1 to activate tracing (auto-set by generate-conftest).
    Set CINTENT_V3_OUTPUT to override the output directory.

To regenerate: python -m cintent_v3 generate-conftest {project_root}
"""

import json
import sys
import os
import time

# Ensure cintent_v3 is importable
sys.path.insert(0, {cintent_v3_path!r})

from cintent_v3.tracer import CallGraphTracer
from cintent_v3.callgraph import export_call_graph

_PROJECT_ROOT = {project_root!r}
_OUTPUT_DIR = os.environ.get("CINTENT_V3_OUTPUT", _PROJECT_ROOT)
_START_TIME = None

_tracer = CallGraphTracer(
    project_root=_PROJECT_ROOT,
    record_external=False,
)


def pytest_runtestloop(session):
    """Start tracing before the test loop begins."""
    global _START_TIME
    _START_TIME = time.time()
    _tracer.start()


def pytest_sessionfinish(session, exitstatus):
    """Stop tracing and export the call graph after tests finish."""
    _tracer.stop()
    elapsed = time.time() - _START_TIME if _START_TIME else 0

    call_graph = _tracer.get_call_graph()
    stats = _tracer.get_stats()

    # Write call graph
    os.makedirs(_OUTPUT_DIR, exist_ok=True)
    cg_path = os.path.join(_OUTPUT_DIR, "cintent_v3_callgraph.json")
    export_call_graph(call_graph, cg_path)

    # Write metadata (for CI artifact consumption)
    metadata = {{
        "tool": "cintent_v3",
        "workspace": os.path.abspath(_PROJECT_ROOT),
        "python_version": sys.version,
        "platform": sys.platform,
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "tracing_seconds": round(elapsed, 2),
        "exit_status": exitstatus,
    }}

    # Collect git info
    import subprocess as _sp
    for key, cmd in [("commit_sha", "git rev-parse HEAD"),
                     ("branch", "git rev-parse --abbrev-ref HEAD"),
                     ("repository", "git config --get remote.origin.url")]:
        try:
            r = _sp.run(cmd.split(), cwd=_PROJECT_ROOT,
                        capture_output=True, text=True, timeout=5)
            if r.returncode == 0:
                metadata[key] = r.stdout.strip()
        except Exception:
            pass

    # CI environment
    if os.environ.get("GITHUB_ACTIONS") == "true":
        metadata["ci_system"] = "github_actions"
        for env_key in ["GITHUB_REPOSITORY", "GITHUB_SHA", "GITHUB_REF",
                        "GITHUB_RUN_ID", "GITHUB_JOB", "GITHUB_WORKFLOW"]:
            val = os.environ.get(env_key)
            if val:
                metadata[env_key.lower()] = val

    meta_path = os.path.join(_OUTPUT_DIR, "cintent_v3_metadata.json")
    with open(meta_path, "w") as f:
        json.dump(metadata, f, indent=2)

    # Write tracing stats
    stats_path = os.path.join(_OUTPUT_DIR, "cintent_v3_stats.json")
    with open(stats_path, "w") as f:
        json.dump(stats, f, indent=2)

    print(f"\\n[cintent_v3] Traced {{stats['unique_edges']}} unique edges "
          f"({{stats['total_calls']}} total calls, "
          f"{{stats['skipped_duplicate']}} deduplicated)")
    print(f"[cintent_v3] Tracing time: {{elapsed:.1f}}s")
    print(f"[cintent_v3] Call graph exported to: {{cg_path}}")
    print(f"[cintent_v3] Metadata exported to:   {{meta_path}}")
'''


class CintentPytestPlugin:
    """Pytest plugin that traces function calls during test execution.

    Register this plugin to automatically capture the call graph:

        tracer = CallGraphTracer(project_root="/path/to/project")
        plugin = CintentPytestPlugin(tracer, output_path="callgraph.json")
        pytest.main(["tests/"], plugins=[plugin])
    """

    def __init__(
        self,
        tracer: CallGraphTracer,
        output_path: str = "cintent_v3_callgraph.json",
    ) -> None:
        self.tracer = tracer
        self.output_path = output_path
        self._start_time: float | None = None

    def pytest_configure(self, config: Any) -> None:
        """Hook: start tracing as early as possible (before collection)."""
        import time
        self._start_time = time.time()
        self.tracer.start()

    def pytest_sessionfinish(self, session: Any, exitstatus: int) -> None:
        """Hook: stop tracing and export after tests finish."""
        import time
        self.tracer.stop()
        elapsed = time.time() - self._start_time if self._start_time else 0

        call_graph = self.tracer.get_call_graph()
        stats = self.tracer.get_stats()

        export_call_graph(call_graph, self.output_path)

        # Write metadata alongside the call graph
        output_dir = os.path.dirname(self.output_path) or "."
        try:
            from cintent_v3.ci import collect_metadata
            metadata = collect_metadata(self.tracer.project_root)
            metadata["tracing_seconds"] = round(elapsed, 2)
            metadata["exit_status"] = exitstatus

            meta_path = os.path.join(output_dir, "cintent_v3_metadata.json")
            with open(meta_path, "w", encoding="utf-8") as f:
                json.dump(metadata, f, indent=2)
        except Exception:
            pass  # Metadata is optional

        print(
            f"\n[cintent_v3] Traced {stats['unique_edges']} unique edges "
            f"({stats['total_calls']} total calls, "
            f"{stats['skipped_duplicate']} deduplicated)"
        )
        print(f"[cintent_v3] Tracing time: {elapsed:.1f}s")
        print(f"[cintent_v3] Call graph exported to: {self.output_path}")


def generate_conftest(project_root: str, output_dir: str | None = None) -> str:
    """Generate a conftest.py for automatic pytest tracing.

    Args:
        project_root: Absolute path to the project root.
        output_dir: Directory to write conftest.py. Defaults to project_root.

    Returns:
        Path to the generated conftest.py.
    """
    if output_dir is None:
        output_dir = project_root

    project_root = os.path.normpath(os.path.abspath(project_root))

    # Find cintent_v3 package path (parent of src/cintent_v3/)
    cintent_v3_src = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    content = CONFTEST_TEMPLATE.format(
        project_root=project_root,
        cintent_v3_path=cintent_v3_src,
    )

    conftest_path = os.path.join(output_dir, "conftest_cintent_v3.py")
    os.makedirs(output_dir, exist_ok=True)
    with open(conftest_path, "w", encoding="utf-8") as f:
        f.write(content)

    return conftest_path
